service: cedrotech

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs18.x
  iam:
    role:
      statements: ${file(./iamroles.yml)}
resources:
  - ${file(./resources.yml)}
functions:
  - ${file(./functions.yml)}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
  prune:
    automatic: true
    number: 1

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline
